### ISSUE TITLE
authorise fail when request access token for particular scope

### ISSUE THREAD

**Issue by catsky** [sethherr/grape-doorkeeper#3]
steps to reproduce
1. create a application
2. authrise without scope
3. go to document page
4. delete the access token
5. go back to document page
6. choose a scope like "write_user" to request a new token
7. click the auth link, it fails with the error showing on the page

```
The requested scope is invalid, unknown, or malformed.
```

proposed fix:
in config file "doorkeeper.rb", change the line from

```
optional_scopes OAUTH_SCOPES
```

to 

```
optional_scopes *OAUTH_SCOPES
```

(unwrap the params)

**Comment by sethherr** [comment]
@catsky thank you!
